#!/bin/bash

# Network Namespace Setup for SOME/IP Applications
# This script creates 3 namespaces: server-ns, client1-ns, client2-ns
# Connected via a bridge to enable multicast communication

echo "Creating network namespaces and bridge setup..."

# Clean up any existing setup
sudo ip netns del server-ns 2>/dev/null || true
sudo ip netns del client1-ns 2>/dev/null || true  
sudo ip netns del client2-ns 2>/dev/null || true
sudo ip link del br0 2>/dev/null || true

# Create namespaces
sudo ip netns add ns0
sudo ip netns add ns1
sudo ip netns add ns2

# Create veth pairs (virtual Ethernet cables)
sudo ip link add veth0 type veth peer name veth0-br
sudo ip link add veth1 type veth peer name veth1-br
sudo ip link add veth2 type veth peer name veth2-br

# Assign veth ends to namespaces
sudo ip link set veth0 netns ns0
sudo ip link set veth1 netns ns1
sudo ip link set veth2 netns ns2

# Create a bridge to connect all veth pairs
sudo ip link add name br0 type bridge
sudo ip link set br0 up
sudo ip link set veth0-br master br0
sudo ip link set veth1-br master br0
sudo ip link set veth2-br master br0
sudo ip link set veth0-br up
sudo ip link set veth1-br up
sudo ip link set veth2-br up

# Inside each namespace, set up veth interface
sudo ip netns exec ns0 ip addr add 192.168.0.1/24 dev veth0
sudo ip netns exec ns1 ip addr add 192.168.0.2/24 dev veth1
sudo ip netns exec ns2 ip addr add 192.168.0.3/24 dev veth2

sudo ip netns exec ns0 ip link set lo up
sudo ip netns exec ns1 ip link set lo up
sudo ip netns exec ns2 ip link set lo up

sudo ip netns exec ns0 ip link set veth0 up
sudo ip netns exec ns1 ip link set veth1 up
sudo ip netns exec ns2 ip link set veth2 up
